---
apiVersion: acid.zalan.do/v1
kind: OperatorConfiguration
metadata:
  name: postgresql-operator
  namespace: telemetry
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: postgres-operator
    app: postgres-operator
configuration:
  kubernetes_use_configmaps: true  # Cannot use endpoints in Openshift per Zalando Docs