apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterRole.nodeExporter.yaml
  - clusterRoleBinding.nodeExporter.yaml
  - daemonSet.nodeExporter.yaml
  - networkPolicy.nodeExporter.yaml
  - service.nodeExporter.yaml
  - serviceAccount.nodeExporter.yaml
  - serviceMonitor.nodeExporter.yaml
  - prometheusRule.nodeExporter.yaml