apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceMonitor.apiServer.yaml
  - serviceMonitor.controllerManager.yaml
  - serviceMonitor.coredns.yaml
  - serviceMonitor.kubelet.yaml
  - serviceMonitor.scheduler.yaml
  - prometheusRule.kubePrometheus.yaml
  - prometheusRule.kubeControlPlane.yaml