{
 "title": "Metrics Collector Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job=\"$job\"}, pod)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up{job=\"$job\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metric Collector Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "gauge",
   "description": "Shows the current phase of the pod or pods. This is not the state of the collector itself. ",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{pod=~\"$pod\"}) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Additional Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "If there is any red in the state pannel to the left, that means the Prometheus collector job **${job}** is down.\r\n\r\n**Pods** this collector is scraping:  ${pod}\r\n\r\n**Namespace**:  ${namespace}"
   }
  },
  {
   "title": "Pod Owner",
   "type": "table",
   "description": "Shows the kind that owns the pod. ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_owner{pod=~\"$pod\"}",
     "legendFormat": "{{owner_kind}} owns \"{{pod}}\""
    }
   ]
  },
  { "title": "Pod CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\"}[5m]))",
     "legendFormat": "$pod"
    }
   ]
  },
  { "title": "Pod RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$pod RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\"})",
     "legendFormat": "Postgres 0"
    }
   ]
  }
 ]
}