apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.telemetry.yaml
  - role.grafana.yaml
  - roleBinding.grafana.yaml
  - serviceAccount.grafana.yaml
  - configMap.grafana-dashboards-provider.yaml
  - configMap.grafana-datasources.yaml
  - configMap.grafana-env.yaml
  - deployment.grafana.yaml
  - service.grafana.yaml
  - ingress.grafana.yaml
  - dashboards
