---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: telemetry
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-main
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: grafana
