# replication-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: super-user-creds
  namespace: nessie
type: Opaque
stringData:
  username: superuser
  password: clio
---
# replication-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-user-creds
  namespace: nessie
type: Opaque
stringData:
  username: clio
  password: clio
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: clio-db
  namespace: nessie
spec:
  instances: 1
  storage:
    size: 1Gi
  superuserSecret:
    name: super-user-creds
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: clio
      owner: clio
      secret:
        name: app-user-creds



