apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nessie
    app.kubernetes.io/name: nessie
    app.kubernetes.io/version: 0.105.0
  name: nessie-env
  namespace: nessie
data:
  # Config
  QUARKUS_HTTP_PORT: "19120"
  QUARKUS_MANAGEMENT_PORT: "9000"

  # S3 Configuration
  NESSIE_WAREHOUSE_DEFAULTWAREHOUSE_S3_ENDPOINT_OVERRIDE: "http://clio-minio-hl.nessie.svc.cluster.local:9000"
  NESSIE_WAREHOUSE_DEFAULTWAREHOUSE_LOCATION: "s3://clio-data-lakehouse/iceberg-warehouse"
  AWS_ACCESS_KEY_ID: console
  AWS_SECRET_ACCESS_KEY: password
  AWS_REGION: "us-east-1"
  S3_PATH_STYLE_ACCESS: "true"
  AWS_S3_PATH_STYLE_ACCESS: "true"
  NESSIE_CATALOG_OBJECTSTORE_S3_PATH_STYLE_ACCESS: "true"

  # Database configuration need both nessie and quarkus for some reason
  NESSIE_VERSION_STORE_TYPE: JDBC
  NESSIE_VERSION_STORE_JDBC_URL: "jdbc:postgresql://clio-db-rw.nessie.svc.cluster.local:5432/clio"
  NESSIE_VERSION_STORE_JDBC_USERNAME: clio
  NESSIE_VERSION_STORE_JDBC_PASSWORD: clio
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://clio-db-rw.nessie.svc.cluster.local:5432/clio"
  QUARKUS_DATASOURCE_USERNAME: clio
  QUARKUS_DATASOURCE_PASSWORD: clio


  # Other Config
  NESSIE_SERVER_SEND_STACKTRACE_TO_CLIENT: "true"
  NESSIE_CATALOG_OBJECT_STORES_HEALTH_CHECK_ENABLED: "false"
  NESSIE_VERSION_STORE_PERSIST_CACHE_INVALIDATIONS_SERVICE_NAMES: nessie-mgmt
  QUARKUS_LOG_CONSOLE_ENABLE: "true"
  QUARKUS_LOG_FILE_ENABLE: "false"
  QUARKUS_LOG_SENTRY: "false"
  QUARKUS_OIDC_TENANT_ENABLED: "false"
  QUARKUS_OTEL_SDK_DISABLED: "true"