apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: nessie
    meta.helm.sh/release-namespace: nessie
  labels:
    app.kubernetes.io/instance: nessie
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nessie
    app.kubernetes.io/version: 0.105.0
    helm.sh/chart: nessie-0.105.0
  name: nessie
  namespace: nessie
