apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: cnpg-system
  name: cluster-podmonitor
spec:
  selector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: metrics