apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: cnpg-system
  name: cnpg-operator-podmonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics