apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.keycloak.yaml
  - deployment.keycloak.yaml
  - ingress.keycloak.yaml
  - service.keycloak.yaml
  - serviceAccount.keycloak.yaml
  - clusterRole.keycloak.yaml
  - clusterRoleBinding.keycloak.yaml



