---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configMap.postgresOperator.yaml
- rbac.postgresOperator.yaml
- deployment.postgresOperator.yaml
- service.postgresOperator.yaml
- operatorConfiguration.postgresOperator.yaml
- ns.zalando.yaml

