apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch-main
    app.kubernetes.io/version: "8.12.2"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ELK
spec:
  version: 8.12.2
  nodeSets:
    - name: main
      count: 1
      config:
        node.store.allow_mmap: false