apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - barman-plugin.yaml
  - barman-cloud-client-tls.yaml
  - barman-cloud-server-tls.yaml
  - ./monitoring
