apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.portainer.yaml
  - ingress.portainer.yaml
  - pvc.portainer.yaml
  - service.portainer.yaml
  - rbac.portainer.yaml
  - serviceAccount.portainer.yaml
  - namespace.portainer.yaml
