apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterRole.prometheus.yaml
  - clusterRoleBinding.prometheus.yaml
  - serviceAccount.prometheus.yaml
  - prometheus.prometheus.yaml
  - prometheus.service.yaml
  - prometheus.serviceMonitor.yaml
  - ingress.prometheus.yaml

