apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.minio-env.yaml
- deployment.minio.yaml
- ingress.minio.yaml
- ns.minio.yaml
- service.minio-api.yaml
- service.minio-http.yaml