apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-tool
  namespace: networktool
  labels:
    app.kubernetes.io/name: network-tool
    app.kubernetes.io/instance: network-tool
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: local-kube-core
