---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - customResourceDefinition.operatorconfigurations.acid.zalan.do.yaml
  - customResourceDefinition.postgresqls.acid.zalan.do.yaml
  - customResourceDefinition.postgresteams.acid.zalan.do.yaml


